print("reda")
print("print ('reda the strong")
print("redael tenean \n reda so puteful hehe")
print(2+99999999)
print ("redael fahl \nأكيد متفق ههههه")
print ("ilove python")
print("print ('iloved python'')")
print   ("reda el fager \n el tenean reda")
print(3+3)
print("redaalfohola \nthis is anew line")
print("hello"+ "redael fohola")
print("hello "+"reda")
print("hello"+" reda")
print("hello"+" "+ "reda")
print("koal khara"+" " "ya ahmed")
print("reda"+" eltenean")
print("hello "+" sign up")
print("reda"+" el fohola")
print("hello"+" "+ "mohamed")
print("redael fager\nel teneen")
print("print ('redael tenean')")
print('print (redael tenaean)')
print('print("redael fager")')
print("hello world help me please\nbrother")
print("hello world "+"reda hahahahahahaha")
print("hello"+" reda")
#hello guyshahahahah
#Debug  حل المشاكل
print("hello"+" " "reda")
