name	=	input	("what is your name?\n")
print	("hello "	+	name)
email	=	input("do you have email in the app\n")
print("you dont have email")
print()
input ("signup\n")
print()
input("enter the password\n")
print("جار المعالجه")
print("تم إنشاء حسابك بنجاح يا علق")